### ISSUE TITLE
Questions about pose

### ISSUE THREAD

**Issue by xxxzhi** [xiexh20/behave-dataset#10]
Hi, Thanks for your dataset.

May I ask how to get 3d joints in the dataset?

**Comment by xxxzhi** [comment]
In addition, Do you have the joint names for person_fit.pkl? It is fitted via SMPLH?

**Comment by xiexh20** [comment]
Hi,

yes, the parameters saved in person_fit.pkl is SMPLH parameters. For the joint names, you can find them in original SMPL and MANO paper. the official library for body models [here](https://github.com/vchoutas/smplx) might also help.

**Comment by xxxzhi** [comment]
Thanks for your quick reply.
