### ISSUE TITLE
Regarding the hand pose parts in the provided pose parameters

### ISSUE THREAD

**Issue by zehongs** [xiexh20/behave-dataset#14]
Hi, thanks for the excellent work!
I'm wondering if the hand pose parameters in the `person_fit.pkl`['pose'][66:156] useful in the dataset? or should I ignore these parameters and focus on the body poses? 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/25296730/192553642-92c3c369-75bc-45a0-953d-2acfd2ed0d80.png">

**Comment by xiexh20** [comment]
Hi， 
the hand pose [66:156] usually does not deviate a lot from the mean SMPLH hand pose. so if you take the mean hand pose, it should be okay most of the time. However, if you set them as zeros the difference will be more significant, as in the zero pose, all fingers are straight.

**Comment by zehongs** [comment]
Thanks for the reply! I used to think that the dataset would give detailed hand poses and be able to form a more detailed contact with the object. Because I see your subjects are wearing special gloves. Anyway, thanks for the well-formatted dataset, and congratulations on your recent paper!

**Comment by xiexh20** [comment]
actually we did record the detailed hand pose with these special gloves. but it turned out the data processing is significantly more difficult than we expected. so our current release does not include that, we are still working on processing these :)
