### ISSUE TITLE
Extracting frames from videos

### ISSUE THREAD

**Issue by anjugopinath** [xiexh20/behave-dataset#16]
I downloaded the frame timestamps.

[frame timestamps](https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/video/date01_time.tar)

How should I extract the frames from the raw color videos? Since it has been captured at 30fps, should I extract it at the same rate?

**Comment by xiexh20** [comment]
you can find the exmple code and usage [here](https://github.com/xiexh20/behave-dataset#generate-images-from-raw-videos).
