### ISSUE TITLE
Different pose fit?

### ISSUE THREAD

**Issue by raulTrial** [xiexh20/behave-dataset#23]
What is the difference between `person_fit.pkl` in `fit_02` and `k[0-3].mocap.json`? Also within  `k[0-3].mocap.json`, why does the shape parameters change a lot too? I assumed, that  `fit_02` had the main SMPLH fits, wheras, indiviual fits would just be a function of the original fit and the extrinsics know from the kinect?

**Comment by xiexh20** [comment]
Hi,

As mentioned in [the dataset structure](https://github.com/xiexh20/behave-dataset#dataset-structure), k[0-3].mocap.json stores FrankMocap detections. While fit02 results are the (pseudo) GT SMPLH fits.
