### ISSUE TITLE
hi, person_fit.ply has 6890 points but readme said it was stored in SMPL+H format

### ISSUE THREAD

**Issue by JasonJ33JYS** [xiexh20/behave-dataset#24]
Hi @xiexh20 
Thanks for your wonderful work. I have used your dataset for several weeks, and I found something that I don't understand.

- I take the data out of `person_fit.ply` and found there are 6890 vertex, but readme said `person_fit.ply` was stored in SMPL+H format. 6890 vertex is for SMPL format; and SMPL+H format should have more vertex.

- and if it is SMPL format, is the order of 6890 vertex the same with SMPL format? 

- when i use SMPLX repository to transform SMPLH to SMPL, I found that `person_fit.ply` don't have `face` key, only have 'vertex' key, and the code go wrong because it needs 'vertex' key in .ply file.

Maybe I miss something, thanks for any help!

**Comment by xiexh20** [comment]
Hi, 

1. The SMPL model and SMPL-H model have the same topology, i.e. same number of vertices and faces. They only differ in the number of joint angle parameters. 
2. Yes, same as SMPL mesh format. 
3. I don't understand your problem. Please give more details. e.g. How do you read the ply file?

**Comment by JasonJ33JYS** [comment]
Thanks a lot for your quick reply! @xiexh20 
For the question3, maybe my expression is not so good, I will try again.

I read the `person_fit.ply` in `fit02 dir` using `plyfile.PlyData module`. like below
```
ply_name = 'transfer_data\meshes\smplh\person_fit2.ply'
plydata = PlyData.read(ply_name)
print(plydata['vertex'].data.shape)
# (6890,)
print(plydata['face'].data.shape)
# (0,)
```
You can see that `plydata` has two elements: vertex and face, but face's shape is 0, which means there is no face in .ply file, and this is why: when I transform SMPL+H to SMPL using the [repo](https://github.com/vchoutas/smplx/tree/main/transfer_model) below, the code got wrong, it tells me there is no face in .ply file.

I set `face = [ ]` in the smplx code, and it worked, but I don't know if the SMPL format result is right or not.

Thanks for your reply, again!

**Comment by JasonJ33JYS** [comment]
And other questions:

- Why there is only one `trans` in `person_fit.pkl`, we have four cameras (four views), should we have four `trans`?

- in `k0.mocap.json`, there are pose and shape estimated by FrankMocap, it is not so accurate compared to the real pose and shape. And the real pose and shape can be obtained by transforming `person_fit.ply ( SMPL+H format)` to `person_fit.pkl ( SMPL format)` using [repo](https://github.com/vchoutas/smplx/tree/main/transfer_model). Do I understand right?

- Why `k0.mocap.json` is stored in SMPL format, but `person_fit.pkl` in `fit02 dir` is stored in SMPL+H format?

- For the same static person, four views should have the same pose and shape? If it is, why four views have four kinds of pose and shape? `k0.mocap.json` `k1.mocap.json` `k2.mocap.json` `k3.mocap.json`

- How do you get `person_fit.pkl`?

- If I have SMPL pose and shape, and I put them in SMPL model to get 3D kp, and I project 3D kp to 2D kp, this 2D kp is more accurate or more not accurate than 2D kp openpose estimate.

I am new in 3d human pose estimation. So maybe my questions are too childish. Thanks for any help! 
Best wishes! @xiexh20

**Comment by xiexh20** [comment]
Hi, 

Sorry for the late reply. I am a bit busy these days.
1. The `trans` parameters is on the camera space of kinect 1. All four views are calibrated and it is known how to transform from one view to another. For example, [here](https://github.com/xiexh20/behave-dataset/blob/main/behave_demo.py#L67).
2. yes.
3. We use FrankMocap estimated pose to initialize our SMPL-H fitting. see Sec. 3 in the paper. 
4. Again, `k*.mocap.json` is the result from FrankMocap. Each image is processed independently, the network prediction can have different outputs. 
5. See paper sec.3 and supp. Sec2.3. 
6. This I haven't tested. But the 3D keypoints are estimated from multi-view. So in theory it should be more accurate.
