### ISSUE TITLE
About the person_fit.pkl and person_fit.ply

### ISSUE THREAD

**Issue by yyvhang** [xiexh20/behave-dataset#28]
Hi, thanks for the great work! When I open the person_fit.ply, I found that the hands are the same in all files, and I check the person_fit.pkl, the pose param size is 156, I guess it contains the hand poses param, is it 156=21x3+15x3+15x3+1x3?(21 means the body pose, 15 means the hand pose, and 1 is the root pose). Besides, following the readme file, you use the V1.2 MANO, but the SMPLH_male(female).pkl in it seems can not fit the hand pose.  Could you please figure out what the '156 params' represents and how to fit the mesh with hand poses?

**Comment by xiexh20** [comment]
Hi, 

Thanks for your interests.
yes, the 156 params represent the SMPL-H parameters, so in total we have 52 joints. This is also reflected in the `SMPLH_*.pkl` files. 

What do you mean by `fitting the mesh with hand poses`? what is your problem setup?
