### ISSUE TITLE
Question: Detailed Computation of SMPL v2v (cm)  and obj. v2v (cm)

### ISSUE THREAD

**Issue by jwings1** [xiexh20/behave-dataset#29]
Hello Maintainers,

I hope this message finds you well. I've been using your dataset for a while now and I've found it to be extremely helpful for my research. However, I've run into a snag with some specific aspects. Specifically, I would like to understand how SMPL v2v (cm)  and obj. v2v (cm) are computed: could you elaborate on the underlying preprocessing (e.g. PA) or postprocessing (e.g. averaging) steps involved? What is the metric used?

Thank you in advance for your time and help.

Best Regards,
Lorenzo

**Comment by xiexh20** [comment]
Hi Lorenzo,

Are you referring to the evaluation metrics used by the BEHAVE method? i.e. the numbers reported in table 2 in our main paper.

We perform Procrustes alignment by combining both human and object meshes together. You can find a reference [here](https://github.com/xiexh20/CHORE/blob/main/recon/eval/pose_utils.py#L19).
After alignment, the v2v error is simply [this function](https://github.com/xiexh20/CHORE/blob/main/recon/evaluate.py#L131)

Best,
