### ISSUE TITLE
Any suggestions on getting the extrinsics of camera 1?

### ISSUE THREAD

**Issue by Steve-Tod** [xiexh20/behave-dataset#32]
Hi, thanks for making this great dataset public. I'm trying to align the pose of this dataset with the AMASS dataset and found the human pose is not in the world coordinate (by world I mean the upright coordinate). 

From [this reply](https://github.com/xiexh20/behave-dataset/issues/4#issuecomment-1130001765), I realized that the word coordinate is set to be the coordinate of camera 1. 

Have you calibrated the extrinsics of camera 1 with respect to the surrounding environment? If not, do you have any suggestions on how to acquire this transformation from camera 1 to any upright coordinate? 

Thank you in advance!

**Comment by xiexh20** [comment]
hi, thank you for your interest.

1. we don't have a reference for the world coordinate, so the camera coordinate is the world coordinate. 
2. the camera coordinate we are using is opencv coordinate, in which y-axis is pointing down, if you want to have y-axis up, simply rotate around x-axis by 180 degree.
