### ISSUE TITLE
text description

### ISSUE THREAD

**Issue by chrenx** [xiexh20/behave-dataset#33]
I wonder if there is any text description paired with each sequence in this dataset since I didn't find any.

**Comment by xiexh20** [comment]
hi, we only have action label for each sequence, which is reflected in the sequence name. 
We don't have detailed text annotation for now.

**Comment by chrenx** [comment]
Thanks for your reply! One more thing I wanna double check with you is that the BEHAVE dataset did not offer detailed data on hand poses right? When I visualize the ground truth, it doesn't seem to be quite detailed for the interaction between hands and obj.

**Comment by xiexh20** [comment]
yes, we did optimize the hand pose a bit to satisfy multiview constraints, but this does not change much. most poses are very similar to mean hand pose
