### ISSUE TITLE
Camera matrix - Should the distortion params be incorporated?

### ISSUE THREAD

**Issue by mnauf** [xiexh20/behave-dataset#5]
I am using a very simple camera matrix 
[[fx, 0, cx], 
[0, fy, cy],
[0, 0, 1]]

Should any other distortion parameters be incorporated like tangential and radial distortion?

**Comment by xiexh20** [comment]
the distortion coefficients are stored in the intrinsic calibration files `calibs/intrinsics/*/calibration.json`.
However, some differentiable renderer does not support these coefficients (e.g. pytorch3d). So I simply don't use them in rendering.
