### ISSUE TITLE
Will you release the train/test code of BEHAVE?

### ISSUE THREAD

**Issue by qixinhu11** [xiexh20/behave-dataset#7]

**Comment by xiexh20** [comment]
yes, we are preparing the release of our training and test code, it will come in the following weeks. stay tuned :-)

**Comment by qixinhu11** [comment]
Thank you, hope to see your code soon! It will definitely benefit the research community.

**Comment by xiexh20** [comment]
Code for BEHAVE model can be accesed here: https://github.com/bharat-b7/BEHAVE
