### ISSUE TITLE
Recover mesh using SMPLH parameters, not exactly match to the provided person_fit.ply

### ISSUE THREAD

**Issue by lijiaman** [xiexh20/behave-dataset#8]
Hi there, 

I tried to convert the person_fit.pkl to a .obj file, but the recovered mesh is a bit lower than the given person_fit.ply. Could you share you code for this conversion? not sure why this happens... I used the SMPLH neutral model. Thanks! 
![Screen Shot 2022-06-27 at 3 18 47 PM](https://user-images.githubusercontent.com/12640532/176045222-101abb18-ad4c-4f41-b14b-d6369da9ad1e.png)

**Comment by xiexh20** [comment]
Hi,

I just uploaded an example script to convert smplh parameters to meshes, please check `tools/smpl_params2mesh.py`.

We use gender specific model, version v1.2.
