### ISSUE TITLE
Complete sequences

### ISSUE THREAD

**Issue by nicolasugrinovic** [xiexh20/behave-dataset#9]
Thanks for releasing this dataset!

One question, the rate for the sequences in the dataset seems to be at 1FPS, is there a way to download the video sequences and perhaps the registration at the original recording rate? I guess something like 30FPS.

Cheers,

**Comment by xiexh20** [comment]
Hello,

Thanks for your interest. 
The data and registration at 30fps are still under processing. There are significantly more data when annotating at 30fps, so we need a bit more time to process and check the registration quality. We will release them as soon as possible.

btw, would you like to share you use case of the data at 30fps? we are also very interested in how people would like to use the data for. 

Best,

**Comment by nicolasugrinovic** [comment]
Hi, 
Thank you for the prompt answer! It is great that you will release the whole video sequences.

**Comment by xiexh20** [comment]
hi,

the full video sequence was released in [our website](https://virtualhumans.mpi-inf.mpg.de/behave/license.html), and you can find the example code to extract frames from video [here](https://github.com/xiexh20/behave-dataset#generate-images-from-raw-videos).
